In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

In [2]:
pd.set_option('display.max_columns', None)
df_original = pd.read_excel("1 - Project Data.xlsx")
df_original.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,Competitor had better devices

In [3]:
X = df_original.drop(columns = ['Churn Label', 'Churn Value', 'Churn Reason'])
y = df_original['Churn Value']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [5]:
def clean(df_original):
    # Mapping
    df_original['Gender'] = df_original.Gender.map({'Female':0, 'Male':1, 0:0, 1:1})
    df_original['Senior Citizen'] = df_original['Senior Citizen'].map({'No':0, 'Yes':1, 0:0, 1:1})
    df_original['Partner'] = df_original.Partner.map({'No':0, 'Yes':1, 0:0, 1:1})
    df_original['Dependents'] = df_original.Dependents.map({'No':0, 'Yes':1, 0:0, 1:1})
    df_original['Total Charges'] = pd.to_numeric(df_original['Total Charges'], errors='coerce')
    df_original['Total Charges'].fillna(0, inplace = True)
    df_original['Paperless Billing'] = df_original['Paperless Billing'].map({'No':0, 'Yes':1, 0:0, 1:1})   

    # OHE
    ohe_columns = ['Payment Method', 'Contract', 'Internet Service', 'Multiple Lines', 'Online Security',
     'Online Backup',
     'Device Protection',
     'Tech Support',
     'Streaming TV',
     'Streaming Movies']
    df_original = pd.get_dummies(df_original, columns = ohe_columns, drop_first = True, dtype = int)

    return df_original

In [6]:
X_train_fe = clean(X_train)
X_test_fe = clean(X_test)

/var/folders/nn/b6p7_ncj4zn9kb5k0qsj4hxm0000gn/T/ipykernel_23366/1076322608.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_original['Total Charges'].fillna(0, inplace = True)
/var/folders/nn/b6p7_ncj4zn9kb5k0qsj4hxm0000gn/T/ipykernel_23366/1076322608.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_original['Total Charges'].fillna(0, inplace = True)

In [7]:
def sanity_check(X, y):
    assert(len(X) == len(y)) , "Lengths dont match"
    assert(all(X.index == y.index)), "Indexs dont match"

In [8]:
sanity_check(X_train, y_train)

In [9]:
Feature_Columns = [
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Paperless Billing',
'Payment Method_Credit card (automatic)',
 'Payment Method_Electronic check',
 'Payment Method_Mailed check',
 'Contract_One year',
 'Contract_Two year',
 'Internet Service_Fiber optic',
 'Internet Service_No',
 'Multiple Lines_No phone service',
 'Multiple Lines_Yes',
 'Online Security_No internet service',
 'Online Security_Yes',
 'Online Backup_No internet service',
 'Online Backup_Yes',
 'Device Protection_No internet service',
 'Device Protection_Yes',
 'Tech Support_No internet service',
 'Tech Support_Yes',
 'Streaming TV_No internet service',
 'Streaming TV_Yes',
 'Streaming Movies_No internet service',
 'Streaming Movies_Yes',
 'Lat_Scaled',
 'Lon_Scaled',
 'Monthly_Charges_Scaled',
 'Total_Charges_Scaled',
 'Tenure_Months_Scaled']

In [10]:
Feature_Columns

['Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Paperless Billing',
 'Payment Method_Credit card (automatic)',
 'Payment Method_Electronic check',
 'Payment Method_Mailed check',
 'Contract_One year',
 'Contract_Two year',
 'Internet Service_Fiber optic',
 'Internet Service_No',
 'Multiple Lines_No phone service',
 'Multiple Lines_Yes',
 'Online Security_No internet service',
 'Online Security_Yes',
 'Online Backup_No internet service',
 'Online Backup_Yes',
 'Device Protection_No internet service',
 'Device Protection_Yes',
 'Tech Support_No internet service',
 'Tech Support_Yes',
 'Streaming TV_No internet service',
 'Streaming TV_Yes',
 'Streaming Movies_No internet service',
 'Streaming Movies_Yes',
 'Lat_Scaled',
 'Lon_Scaled',
 'Monthly_Charges_Scaled',
 'Total_Charges_Scaled',
 'Tenure_Months_Scaled']

In [11]:
scaler = MinMaxScaler()
scale_cols = ['Latitude', 'Longitude', 'Monthly Charges', 'Total Charges', 'Tenure Months']
scaler.fit(X_train_fe[scale_cols])
X_train_fe[['Lat_Scaled', 'Lon_Scaled', 'Monthly_Charges_Scaled', 'Total_Charges_Scaled', 'Tenure_Months_Scaled']] = scaler.transform(X_train_fe[scale_cols])
X_test_fe[['Lat_Scaled', 'Lon_Scaled', 'Monthly_Charges_Scaled', 'Total_Charges_Scaled','Tenure_Months_Scaled']] = scaler.transform(X_test_fe[scale_cols])

In [12]:
X_train_fe.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Paperless Billing,Monthly Charges,Total Charges,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check,Contract_One year,Contract_Two year,Internet Service_Fiber optic,Internet Service_No,Multiple Lines_No phone service,Multiple Lines_Yes,Online Security_No internet service,Online Security_Yes,Online Backup_No internet service,Online Backup_Yes,Device Protection_No internet service,Device Protection_Yes,Tech Support_No internet service,Tech Support_Yes,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No internet service,Streaming Movies_Yes,Lat_Scaled,Lon_Scaled,Monthly_Charges_Scaled,Total_Charges_Scaled,Tenure_Months_Scaled
2047,1984-GPTEH,1,United States,California,Burbank,91506,"34.169706, -118.323548",34.169706,-118.323548,0,0,0,0,29,Yes,0,25.15,702.00,0,1,0,0,0,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,0.171574,0.591368,0.068657,0.080946,0.402778
6892,8148-WOCMK,1,United States,California,Castaic,91384,"34.506627, -118.699048",34.506627,-118.699048,1,0,1,1,8,Yes,0,19.60,125.00,1,0,0,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0.207393,0.554221,0.013433,0.014413,0.111111
711,8225-BTJAU,1,United States,California,Stinson Beach,94970,"37.921137, -122.657562",37.921137,-122.657562,1,1,0,0,10,Yes,1,79.25,793.55,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.570395,0.162617,0.606965,0.091502,0.138889
2578,6169-PPETC,1,United States,California,Brentwood,94513,"37.908242, -121.682472",37.908242,-121.682472,1,0,1,1,35,Yes,0,20.50,759.35,0,0,0,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0.569024,0.259080,0.022388,0.087559,0.486111
4472,6036-TTFYU,1,United States,California,Thousand Oaks,91362,"34.191842, -118.822796",34.191842,-118.822796,0,0,1,0,16,Yes,0,19.60,314.45,0,0,1,0,0,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0.173927,0.541979,0.013433,0.036258,0.222222

In [13]:
X_train_fe = X_train_fe[Feature_Columns]
X_test_fe = X_test_fe[Feature_Columns]

In [14]:
X_test_fe.head()

,Gender,Senior Citizen,Partner,Dependents,Paperless Billing,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check,Contract_One year,Contract_Two year,Internet Service_Fiber optic,Internet Service_No,Multiple Lines_No phone service,Multiple Lines_Yes,Online Security_No internet service,Online Security_Yes,Online Backup_No internet service,Online Backup_Yes,Device Protection_No internet service,Device Protection_Yes,Tech Support_No internet service,Tech Support_Yes,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No internet service,Streaming Movies_Yes,Lat_Scaled,Lon_Scaled,Monthly_Charges_Scaled,Total_Charges_Scaled,Tenure_Months_Scaled
23,0,1,1,1,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,0,1,0.146759,0.590468,0.798507,0.289941,0.347222
342,0,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0.831007,0.076742,0.790050,0.369855,0.472222
6610,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0.809615,0.314664,0.369154,0.106141,0.236111
40,0,0,1,1,1,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0.185062,0.599154,0.857214,0.027997,0.027778
1234,1,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0.595555,0.275131,0.663184,0.353672,0.500000

In [15]:
log_reg = LogisticRegression(random_state = 1024)
model = log_reg.fit(X_train_fe, y_train)

In [16]:
model.score(X_train_fe, y_train)

0.8154064607738729

In [17]:
model.score(X_test_fe, y_test)

0.8019872249822569